name: call_mode
description: A plugin for getting/listening to a current call mode
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.0.2

dev_dependencies:
  mocktail: 1.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kardenvan.call_mode
        pluginClass: CallModePlugin
      ios:
        pluginClass: CallModePlugin
