name: call_mode
description: A handy plugin for retrieving and observing a current call mode
version: 0.1.1
repository: https://github.com/kardenvan7/call_mode/tree/0.1.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  mocktail: 1.0.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kardenvan.call_mode
        pluginClass: CallModePlugin
      ios:
        pluginClass: CallModePlugin
